name: "Korber-Maven-Demo"

on: 
  workflow_dispatch:
  
permissions:
  actions: read # For detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  security-events: write # Required for uploading code scanning
  attestations: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OIDC_AUDIENCE: 'korber-workshop'
      OIDC_PROVIDER: 'korber-workshop-github-oidc'
      MAVEN_REPO: 'korber-workshop-maven-dev'
      BUILD_NAME: "maven-build"
      BUILD_ID: "${{github.run_number}}"

    defaults:
      run:
        working-directory: maven-examples/maven-jib-example
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
        with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}

      - name: Run JFrog CLI Ping
        run: jf rt ping

      - name: Configure Maven repositories in JFrog CLI
        run: |
          jf mvnc --repo-resolve-releases ${{ env.MAVEN_REPO }} \
                  --repo-resolve-snapshots ${{ env.MAVEN_REPO }} \
                  --repo-deploy-releases ${{ env.MAVEN_REPO }} \
                  --repo-deploy-snapshots ${{ env.MAVEN_REPO }}

      - name: JFrog Xray Audit command
        run: jf audit
        
      - name: Build and Install Maven Project
        run: jf mvn clean install -DskipTests --build-name=${{env.BUILD_NAME}} --build-number=${{env.BUILD_ID}}

      - name: Collect Env
        run: jf rt bce ${{env.BUILD_NAME}} ${{env.BUILD_ID}} 

      - name: Collect VCS info
        run: jf rt bag ${{env.BUILD_NAME}} ${{env.BUILD_ID}} 

      - name: Publish build
        run: jf rt bp ${{env.BUILD_NAME}} ${{env.BUILD_ID}}
